on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run compile

      - name: Package
        run: npm run package

      - name: Parse version from package.json
        run: |
          echo "EXT_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: templ-${{ env.EXT_VERSION }}.vsix
          path: ./templ-${{ env.EXT_VERSION }}.vsix

      - name: Create release and upload release asset
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ env.EXT_VERSION }}",
              name: "v${{ env.EXT_VERSION }}",
              draft: false,
              prerelease: false,
              generate_release_notes: true
            });

            const path = "./templ-${{ env.EXT_VERSION }}.vsix";
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              data: fs.readFileSync(path),
              name: "templ-${{ env.EXT_VERSION }}.vsix",
              headers: {
                "content-type": "application/vsix",
                "content-length": fs.statSync(path).size
              }
            });

            core.summary.addLink(`Release v${{ env.EXT_VERSION }}`, release.data.html_url);
            await core.summary.write();

