on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build
        run: npm run compile
      - name: Package
        run: npm run package
      - name: Parse version from package.json
        run: |
          echo "EXT_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: templ-${{ env.EXT_VERSION }}.vsix
          path: ./templ-${{ env.EXT_VERSION }}.vsix
